apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    fluxcd.io/sync-checksum: 9abed2609f84996d7ca41eff8e6a68f3b7c8e593
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"fluxcd.io/sync-checksum":"9abed2609f84996d7ca41eff8e6a68f3b7c8e593"},"labels":{"fluxcd.io/sync-gc-mark":"sha256.E6qZ74yXTH_JIqTf0MHAlBO7oEctFLi_txRy6HVKgJk"},"name":"logic-app","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"logic-app"}},"template":{"metadata":{"labels":{"app":"logic-app"}},"spec":{"containers":[{"image":"tkubica/lapp:v1","name":"logic-app","ports":[{"containerPort":80,"name":"http"}]}]}}}}
  creationTimestamp: "2020-09-23T11:41:31Z"
  generation: 2
  labels:
    fluxcd.io/sync-gc-mark: sha256.E6qZ74yXTH_JIqTf0MHAlBO7oEctFLi_txRy6HVKgJk
  name: logic-app
  namespace: default
  resourceVersion: "4716128"
  selfLink: /apis/apps/v1/namespaces/default/deployments/logic-app
  uid: d5162506-7848-47bc-a3d9-3f1baa4b28b6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: logic-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: logic-app
    spec:
      containers:
      - image: tkubica/lapp:v1
        imagePullPolicy: IfNotPresent
        name: logic-app
        env:
        - name: WEBSITE_HOSTNAME
          value: lapp.aks.azurepraha.com
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-09-23T13:05:40Z"
    lastUpdateTime: "2020-09-23T13:05:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-09-23T13:05:40Z"
    lastUpdateTime: "2020-09-23T13:05:40Z"
    message: ReplicaSet "logic-app-6bb866ddf8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
