apiVersion: apps/v1
kind: Deployment
metadata:
  name: customvision-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customvision-api
  template:
    metadata:
      labels:
        app: customvision-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: customvision-api
        image: tkubica/plysaci:latest
        ports:
        - containerPort: 80
          name: http