apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-app1
  labels:
    app: opentelemetry-app1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: opentelemetry-app1
    spec:
      containers:
        - name: opentelemetry-app1
          image: tkubica/opentelemetry:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.labels['app']"
            - name: APPINSIGHTS_INSTRUMENTATION_KEY
              valueFrom:
                secretKeyRef:
                  name: applicationinsights
                  key: key
            - name: REMOTE_ENDPOINT
              value: "http://opentelemetry-app2:8080/data"
          resources:
            requests:
                cpu: 10m
                memory: 16M
            limits:
                cpu: 100M
                memory: 128M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-app2
  labels:
    app: opentelemetry-app2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: opentelemetry-app2
    spec:
      containers:
        - name: opentelemetry-app2
          image: tkubica/opentelemetry:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.labels['app']"
            - name: APPINSIGHTS_INSTRUMENTATION_KEY
              valueFrom:
                secretKeyRef:
                  name: applicationinsights
                  key: key
            - name: REMOTE_ENDPOINT
              value: "http://opentelemetry-app1:8080/data"
          resources:
            requests:
                cpu: 10m
                memory: 16M
            limits:
                cpu: 100M
                memory: 128M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-tfgen
  labels:
    app: opentelemetry-tfgen
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: opentelemetry-tfgen
    spec:
      containers:
        - name: opentelemetry-tfgen
          image: tkubica/opentelemetry-tfgen:latest
          env:
            - name: APP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.labels['app']"
            - name: APPINSIGHTS_INSTRUMENTATION_KEY
              valueFrom:
                secretKeyRef:
                  name: applicationinsights
                  key: key
            - name: REMOTE_ENDPOINT1
              value: "http://opentelemetry-app1:8080"
            - name: REMOTE_ENDPOINT2
              value: "http://opentelemetry-app2:8080"
          resources:
            requests:
                cpu: 10m
                memory: 16M
            limits:
                cpu: 100M
                memory: 128M
---
kind: Service
apiVersion: v1
metadata:
  name: opentelemetry-app1
  labels:
    app: opentelemetry-app1
spec:
  selector:
    app: opentelemetry-app1
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: opentelemetry-app2
  labels:
    app: opentelemetry-app2
spec:
  selector:
    app: opentelemetry-app2
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 8080