apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 32Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sql
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
        resources:
          requests:
            cpu: 1
            memory: 2.1G
          limits:
            cpu: 2
            memory: 3G
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: sql-disk
---
apiVersion: v1
kind: Service
metadata:
  name: sql
spec:
  selector:
    app: sql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer